CREATE TABLE grupos_musculares(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255)
);

INSERT INTO grupos_musculares (nome, descricao) VALUES
    ('Peito', 'Peitoral maior e menor'),
    ('Costas', 'Dorsais, romboides e trapézio'),
    ('Pernas', 'Quadríceps, posterior e panturrilha'),
    ('Ombros', 'Deltoides'),
    ('Bíceps', 'Flexores de cotovelo'),
    ('Tríceps', 'Extensores de cotovelo'),
    ('Abdômen', 'Reto abdominal e oblíquos'),
    ('Glúteos', 'Glúteo máximo, médio e mínimo');

CREATE TABLE exercicios(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255),
    url_video VARCHAR(255),
    grupo_muscular_id BIGINT NOT NULL,
    CONSTRAINT fk_exercicios_grupo FOREIGN KEY (grupo_muscular_id) REFERENCES grupos_musculares(id)
);

CREATE TABLE fichas(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT NOT NULL,
    instrutor_id BIGINT NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE,
    CONSTRAINT fk_fichas_aluno FOREIGN KEY (aluno_id) REFERENCES alunos (id) ON DELETE CASCADE,
    CONSTRAINT fk_fichas_instrutor FOREIGN KEY (instrutor_id) REFERENCES instrutores (id)
);

CREATE TABLE itens_ficha(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ficha_id BIGINT NOT NULL,
    exercicio_id BIGINT NOT NULL,
    ordem INT NOT NULL,
    series INT NOT NULL,
    repeticoes_min INT NOT NULL,
    repeticoes_max INT NOT NULL,
    descanso INT NOT NULL,
    CONSTRAINT fk_itens_ficha FOREIGN KEY (ficha_id) REFERENCES fichas (id) ON DELETE CASCADE,
    CONSTRAINT fk_itens_exercicio FOREIGN KEY (exercicio_id) REFERENCES exercicios (id) ON DELETE CASCADE
);

CREATE TABLE execucoes_treino(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT NOT NULL,
    item_ficha_id BIGINT NOT NULL,
    numero_serie INT NOT NULL,
    carga_utilizada DOUBLE PRECISION,
    repeticoes INT,
    hora_inicio TIMESTAMP,
    hora_fim TIMESTAMP,
    observacao VARCHAR(255),
    CONSTRAINT fk_execucoes_aluno FOREIGN KEY (aluno_id) REFERENCES alunos (id) ON DELETE CASCADE,
    CONSTRAINT fk_execucoes_item FOREIGN KEY (item_ficha_id) REFERENCES itens_ficha (id) ON DELETE CASCADE
);