CREATE TABLE alunos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    telefone VARCHAR(255),
    sexo VARCHAR(255),
    data_nascimento DATE,
    objetivos VARCHAR(255),
    observacoes VARCHAR(255),
    CONSTRAINT uk_alunos_email UNIQUE (email)
);