CREATE TABLE instrutores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    telefone VARCHAR(255),
    sexo VARCHAR(255),
    data_nascimento DATE,
    cref VARCHAR(255) NOT NULL,
    CONSTRAINT uk_instrutores_email UNIQUE (email)
);