CREATE TABLE avaliacoes(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT NOT NULL,
    data_avaliacao DATE NOT NULL,
    observacoes VARCHAR(255),
    CONSTRAINT fk_avaliacoes_aluno FOREIGN KEY (aluno_id) REFERENCES alunos (id)
);