CREATE TABLE medidas_corporais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id BIGINT NOT NULL,
    peso DOUBLE PRECISION,
    imc DOUBLE PRECISION,
    percentual_gordura DOUBLE PRECISION,
    CONSTRAINT fk_medidas_avaliacao FOREIGN KEY (avaliacao_id) REFERENCES avaliacoes (id),
    CONSTRAINT uk_medidas_avaliacao UNIQUE (avaliacao_id)
);

CREATE TABLE medida_circunferencias (
    medida_corporal_id BIGINT NOT NULL,
    tipo VARCHAR(255),
    valor_cm DOUBLE PRECISION,
    CONSTRAINT fk_circunferencias_medida FOREIGN KEY (medida_corporal_id) REFERENCES medidas_corporais (id)
);