CREATE TABLE fotografias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id BIGINT NOT NULL,
    caminho_arquivo VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    data_upload TIMESTAMP NOT NULL,
    CONSTRAINT fk_fotografias_avaliacao FOREIGN KEY (avaliacao_id) REFERENCES avaliacoes (id)
);