CREATE TABLE desvios_posturais(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id BIGINT NOT NULL,
    regiao VARCHAR(255) NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    severidade VARCHAR(255) NOT NULL,
    CONSTRAINT fk_desvios_avaliacao FOREIGN KEY (avaliacao_id) REFERENCES avaliacoes (id)
);